on: 
  pull_request:
    branches:
      - main

name: Test app
jobs:
  test:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.10.0'
    - run: flutter pub get
    - run: flutter pub run build_runner build --delete-conflicting-outputs
    - run: flutter test --coverage